(() => {
  const URL = 'https://sktpjacowqaedddtrhuz.supabase.co';
  const KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrdHBqYWNvd3FhZWRkZHRyaHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2NDk5MzEsImV4cCI6MjA5NDIyNTkzMX0.FK4N_ATFTaUuGXrYu_7OBn3qCdlo0rOzxk-E6TxJxqs';
  const local = { 'callaloo soup':'../assets/heritage/callaloo.jpg','trinidadian callaloo':'../assets/heritage/callaloo.jpg','oil down':'../assets/heritage/oil-down.jpg','pholourie':'../assets/heritage/pholourie.jpg','sahina':'../assets/heritage/sahina.png','chicken pelau':'../assets/heritage/pelau.jpg' };
  const slug = t => String(t).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const fallback = (img,title) => { img.onerror=null; img.src=local[String(title).toLowerCase()] || 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 1000"><rect width="100%" height="100%" fill="#E87722"/><text x="50%" y="50%" fill="white" font-size="42" font-family="serif" text-anchor="middle">${title}</text></svg>`); };
  async function init(){ const grid=document.querySelector('.recipe-grid'); if(!grid)return; try{ const r=await fetch(`${URL}/rest/v1/recipes?select=id,title,description,cover_photo_url,vibe_tags,calories_per_serving,prep_time_mins,cook_time_mins&is_published=eq.true&order=title.asc`,{headers:{apikey:KEY,Authorization:`Bearer ${KEY}`}}); if(!r.ok)throw 0; const rows=await r.json(); grid.innerHTML=rows.map(x=>`<article class="recipe-card" data-recipe-id="${x.id}"><img src="${esc(x.cover_photo_url||'')}" onerror="fallback(this,'${esc(x.title)}')" class="recipe-image" alt="${esc(x.title)}"><div class="recipe-content"><h3>${esc(x.title)}</h3><div class="recipe-meta"><span>${esc((x.vibe_tags||[])[0]||'Caribbean Heritage')}</span><span>${x.calories_per_serving ? esc(x.calories_per_serving)+' kcal' : ''}</span></div></div></article>`).join(''); window.fallback=fallback; }catch{ /* keep the local archive visible if the database is unavailable */ } }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
